# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *
from backend import *



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1128, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 291, 121))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Desktop/ObshVid.PNG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.img_picture = QtWidgets.QLabel(self.centralwidget)
        self.img_picture.setGeometry(QtCore.QRect(20, 140, 291, 121))
        self.img_picture.setText("")
        self.img_picture.setPixmap(QtGui.QPixmap("../../Desktop/MainTask.PNG"))
        self.img_picture.setScaledContents(True)
        self.img_picture.setObjectName("img_picture")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(340, 10, 171, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.m_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.m_line.setObjectName("m_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.m_line)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.n_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.n_line.setObjectName("n_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.n_line)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.N_max_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.N_max_line.setObjectName("N_max_line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.N_max_line)
        self.eps_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.eps_line.setObjectName("eps_line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eps_line)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.omega_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.omega_line.setObjectName("omega_line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.omega_line)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 300, 641, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.v_list = QtWidgets.QWidget()
        self.v_list.setObjectName("v_list")
        self.v_table = QtWidgets.QTableWidget(self.v_list)
        self.v_table.setGeometry(QtCore.QRect(0, 0, 641, 471))
        self.v_table.setObjectName("v_table")
        self.v_table.setColumnCount(1)
        self.v_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.v_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.v_table.setHorizontalHeaderItem(0, item)
        self.tabWidget.addTab(self.v_list, "")
        self.f_list = QtWidgets.QWidget()
        self.f_list.setObjectName("f_list")
        self.f_table = QtWidgets.QTableWidget(self.f_list)
        self.f_table.setGeometry(QtCore.QRect(0, 0, 641, 471))
        self.f_table.setObjectName("f_table")
        self.f_table.setColumnCount(1)
        self.f_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.f_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.f_table.setHorizontalHeaderItem(0, item)
        self.tabWidget.addTab(self.f_list, "")
        self.matrix_list = QtWidgets.QWidget()
        self.matrix_list.setObjectName("matrix_list")
        self.matrix_table = QtWidgets.QTableWidget(self.matrix_list)
        self.matrix_table.setGeometry(QtCore.QRect(0, 0, 641, 471))
        self.matrix_table.setObjectName("matrix_table")
        self.matrix_table.setColumnCount(1)
        self.matrix_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.matrix_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.matrix_table.setHorizontalHeaderItem(0, item)
        self.tabWidget.addTab(self.matrix_list, "")
        self.right_list = QtWidgets.QWidget()
        self.right_list.setObjectName("right_list")
        self.right_table = QtWidgets.QTableWidget(self.right_list)
        self.right_table.setGeometry(QtCore.QRect(0, 0, 641, 471))
        self.right_table.setObjectName("right_table")
        self.right_table.setColumnCount(1)
        self.right_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.right_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.right_table.setHorizontalHeaderItem(0, item)
        self.tabWidget.addTab(self.right_list, "")
        self.solve_button = QtWidgets.QPushButton(self.centralwidget)
        self.solve_button.setGeometry(QtCore.QRect(340, 220, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.solve_button.setFont(font)
        self.solve_button.setObjectName("solve_button")
        self.solve_button_test = QtWidgets.QPushButton(self.centralwidget)
        self.solve_button_test.setGeometry(QtCore.QRect(500, 220, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.solve_button_test.setFont(font)
        self.solve_button_test.setObjectName("solve_button_test")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "m:"))
        self.label_4.setText(_translate("MainWindow", "n:"))
        self.label_5.setText(_translate("MainWindow", "N макс:"))
        self.label_6.setText(_translate("MainWindow", "eps:"))
        self.label_7.setText(_translate("MainWindow", "omega:"))
        item = self.v_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "y"))
        item = self.v_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "x"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.v_list), _translate("MainWindow", "Матрица решений (Vij)"))
        item = self.f_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "y"))
        item = self.f_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "x"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.f_list), _translate("MainWindow", "Значения функции в узлах сетки"))
        item = self.matrix_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "y"))
        item = self.matrix_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "x"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.matrix_list), _translate("MainWindow", "Элементы матрицы СЛАУ"))
        item = self.right_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "y"))
        item = self.right_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "x"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.right_list), _translate("MainWindow", "Элементы правой части"))
        self.solve_button.setText(_translate("MainWindow", "Решить!"))
        self.solve_button_test.setText(_translate("MainWindow", "Решить \n"
"тестовую задачу"))

        self.n_line.setText('4')
        self.m_line.setText('4')
        self.N_max_line.setText('1000')
        self.eps_line.setText('1e-12')
        self.omega_line.setText('1.5')

        self.solve_button.clicked.connect(lambda: self.setTable1())
        self.solve_button_test.clicked.connect(lambda: self.setTable())

    def setTable(self):
        v_list = Zeydel_solve_test(int(self.n_line.text()), int(self.m_line.text()), int(self.N_max_line.text()),
                              float(self.eps_line.text()), float(self.omega_line.text()))[0]
        f_list = Zeydel_solve_test(int(self.n_line.text()), int(self.m_line.text()), int(self.N_max_line.text()),
                              float(self.eps_line.text()), float(self.omega_line.text()))[4]

        self.v_table.setRowCount((int(self.m_line.text()) + 1))
        self.v_table.setColumnCount((int(self.n_line.text()) + 1))

        self.f_table.setRowCount((int(self.m_line.text()) + 1))
        self.f_table.setColumnCount((int(self.n_line.text()) + 1))

        self.right_table.setRowCount((int(self.m_line.text()) - 1) * (int(self.n_line.text()) - 1))

        matrix = setMatrix(int(self.n_line.text()), int(self.m_line.text()))
        solve_vector = set_solve_vector(int(self.n_line.text()), int(self.m_line.text()))[0]

        self.matrix_table.setRowCount((int(self.m_line.text()) - 1) * (int(self.n_line.text()) - 1))
        self.matrix_table.setColumnCount((int(self.m_line.text()) - 1) * (int(self.n_line.text()) - 1))

        for i in range((int(self.m_line.text()) - 1) * (int(self.n_line.text()) - 1)):
            self.right_table.setItem(0, i, QTableWidgetItem(str(solve_vector[i])))
            for j in range((int(self.m_line.text()) - 1) * (int(self.n_line.text()) - 1)):
                self.matrix_table.setItem(i, j, QTableWidgetItem(str(matrix[i][j])))

        for i in range((int(self.m_line.text()) + 1)):
            for j in range((int(self.n_line.text()) + 1)):
                self.v_table.setItem(i, j, QTableWidgetItem(str(v_list[i][j])))
                self.f_table.setItem(i, j, QTableWidgetItem(str(f_list[i][j])))


    def setTable1(self):

        v_list = Zeydel_solve(int(self.n_line.text()), int(self.m_line.text()), int(self.N_max_line.text()),
                              float(self.eps_line.text()), float(self.omega_line.text()))[0]
        f_list = Zeydel_solve(int(self.n_line.text()), int(self.m_line.text()), int(self.N_max_line.text()),
                              float(self.eps_line.text()), float(self.omega_line.text()))[4]

        self.v_table.setRowCount((int(self.m_line.text()) + 1))
        self.v_table.setColumnCount((int(self.n_line.text()) + 1))

        self.f_table.setRowCount((int(self.m_line.text()) + 1))
        self.f_table.setColumnCount((int(self.n_line.text()) + 1))

        self.right_table.setRowCount((int(self.m_line.text()) - 1) * (int(self.n_line.text()) - 1))

        matrix = setMatrix2(int(self.n_line.text()), int(self.m_line.text()))
        solve_vector = set_solve_vector(int(self.n_line.text()), int(self.m_line.text()))[0]

        self.matrix_table.setRowCount((int(self.m_line.text()) - 1) * (int(self.n_line.text()) - 1))
        self.matrix_table.setColumnCount((int(self.m_line.text()) - 1) * (int(self.n_line.text()) - 1))

        for i in range((int(self.m_line.text()) - 1) * (int(self.n_line.text()) - 1)):
            self.right_table.setItem(0, i, QTableWidgetItem(str(solve_vector[i])))
            for j in range((int(self.m_line.text()) - 1) * (int(self.n_line.text()) - 1)):
                self.matrix_table.setItem(i, j, QTableWidgetItem(str(matrix[i][j])))

        for i in range((int(self.m_line.text()) + 1)):
            for j in range((int(self.n_line.text()) + 1)):
                self.v_table.setItem(i, j, QTableWidgetItem(str(v_list[i][j])))
                self.f_table.setItem(i, j, QTableWidgetItem(str(f_list[i][j])))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
